apiVersion: v2
name: training
description: A Helm chart for deploying a training service
type: application
version: 0.0.1
dependencies:
  - name: common
    version: 0.0.1
    repository: file://../common
