{{- with .Values.postgres }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .name }}
spec:
  selector:
    matchLabels:
      app: {{ .name }}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: {{ .name }}
    spec:
      containers:
        - name: {{ .name }}
          image: "{{ .image.url }}:{{ .image.tag }}"
          env:
            - name: POSTGRES_PASSWORD
              value: {{ .password | quote }}
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
          ports:
            {{- range .ports }}
            - containerPort: {{ .port }}
              name: postgre-{{ .port }}
            {{- end }}
          readinessProbe:
            {{- range .ports }}
            {{- if eq .protocol "TCP" }}
            tcpSocket:
              port: {{ .port }}
            initialDelaySeconds: 5
            periodSeconds: 10
            {{- end }}
            {{- end }}
          volumeMounts:
            - name: {{ .name }}-data
              mountPath: /var/lib/postgresql/data/
      volumes:
        - name: {{ .name }}-data
          persistentVolumeClaim:
            claimName: {{ .name }}
{{- end }}
