image: curlimages/curl:latest

variables:
  ARTIFACT_REPOSITORY_ID: 2358

stages:
  - build
  - upload

build:
  stage: build
  image:
    name: alpine/helm
    entrypoint: ["/bin/sh", "-c"]
  script:
    - helm package helm/kypo-certs/
    - helm package helm/kypo-crp-head/
    - helm package helm/kypo-gen-users/
    - helm package helm/kypo-postgres/
  artifacts:
    paths:
    - kypo-certs-*.tgz
    - kypo-crp-head-*.tgz
    - kypo-gen-users-*.tgz
    - kypo-postgres-*.tgz
    expire_in: 1 week

upload:
  stage: upload
  script:
    - if [ "$CI_COMMIT_BRANCH" = "master" ]; then export CHANNEL="stable"; else export CHANNEL="devel"; fi
    - echo "Uploading to ${CHANNEL} channel."
    - 'curl --request POST --user $CI_CUSTOM_REGISTRY_USER:$CI_CUSTOM_REGISTRY_PASSWORD --form "chart=@`ls kypo-certs-*.tgz`" "${CI_API_V4_URL}/projects/${ARTIFACT_REPOSITORY_ID}/packages/helm/api/${CHANNEL}/charts"'
    - 'curl --request POST --user $CI_CUSTOM_REGISTRY_USER:$CI_CUSTOM_REGISTRY_PASSWORD --form "chart=@`ls kypo-crp-head-*.tgz`" "${CI_API_V4_URL}/projects/${ARTIFACT_REPOSITORY_ID}/packages/helm/api/${CHANNEL}/charts"'
    - 'curl --request POST --user $CI_CUSTOM_REGISTRY_USER:$CI_CUSTOM_REGISTRY_PASSWORD --form "chart=@`ls kypo-gen-users-*.tgz`" "${CI_API_V4_URL}/projects/${ARTIFACT_REPOSITORY_ID}/packages/helm/api/${CHANNEL}/charts"'
    - 'curl --request POST --user $CI_CUSTOM_REGISTRY_USER:$CI_CUSTOM_REGISTRY_PASSWORD --form "chart=@`ls kypo-postgres-*.tgz`" "${CI_API_V4_URL}/projects/${ARTIFACT_REPOSITORY_ID}/packages/helm/api/${CHANNEL}/charts"'
