{{- define "common.pvc" -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .name }}
  labels: {{- include "common.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .pvc.accessMode | default "ReadWriteOnce" }}
  storageClassName: {{ .pvc.storageClassName }}
  resources:
    requests:
      storage: {{ .pvc.size }}
{{- end }}
