apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: git-internal-key
  labels:
    app: {{ .Values.name }}
  annotations:
    "helm.sh/hook": "pre-install"
    "helm.sh/hook-delete-policy": "before-hook-creation"
data:
  git-ssh-key: {{ genPrivateKey "ecdsa" | b64enc }}
