{{- with .Values.oidcIssuerApp }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .name }}
  labels: {{- include "common.labels" (dict "name" .name "chart" $.Chart "release" $.Release "extraLabels" .extraLabels) | nindent 4 }}
spec:
  replicas: {{ .replicasCount }}
  selector:
    matchLabels: {{- include "common.matchLabels" (dict "name" .name "release" $.Release) | nindent 6 }}
  template:
    metadata:
      labels: {{- include "common.labels" (dict "name" .name "chart" $.Chart "release" $.Release "extraLabels" .extraLabels) | nindent 8 }}
    spec:
      containers:
        - name: {{ .name }}
          image: "{{ .image.url }}:{{ .image.tag }}"
          env:
            - name: POSTGRES_DBNAME
              value: {{ $.Values.postgresServices.oidcIssuer.dbName | quote }}
            - name: POSTGRES_USERNAME
              value: {{ $.Values.postgresServices.oidcIssuer.dbUser | quote }}
            - name: POSTGRES_PASSWORD
              value: {{ $.Values.postgresServices.oidcIssuer.dbPassword | quote }}
            - name: POSTGRES_CONTAINER_NAME
              value: {{ $.Values.global.postgres.serviceName | quote }}
            - name: OPENDJ_CONTAINER_NAME
              value: {{ $.Values.oidcIssuerLdap.name | quote }}
          ports:
            {{- range .ports }}
            - containerPort: {{ .port }}
              name: oidcapp-{{ .port }}
            {{- end }}
          readinessProbe:
            {{- range .ports }}
            tcpSocket:
              port: {{ .port }}
            initialDelaySeconds: 5
            periodSeconds: 10
            {{- end }}
          volumeMounts:
            - name: {{ .name }}-config
              mountPath: /app/etc
            - name: {{ .name }}-data
              mountPath: /opt/oidc-config
      volumes:
        - name: {{ .name }}-config
          secret:
            secretName: {{ .name }}
        - name: {{ .name }}-data
          persistentVolumeClaim:
            claimName: {{ .name }}
{{- end }}
