{{- $ldapPort := first .Values.oidcIssuerLdap.ports -}}
{{- with .Values.oidcIssuerApp }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .name }}
type: Opaque
stringData:
  csirtmu-dummy-issuer.properties: |-
    csirtmu.oidc.dummy.issuer.forceHttps=true
    csirtmu.oidc.dummy.issuer.protocol=https
    csirtmu.oidc.dummy.issuer.host={{ $.Values.global.kypoCrpHost }}
    csirtmu.oidc.dummy.issuer.port={{ .external_port }}
    csirtmu.oidc.dummy.issuer.contextPath=csirtmu-dummy-issuer-server
    #
    # LDAP config
    #
    csirtmu.oidc.dummy.ldap.server=ldap://{{ $.Values.oidcIssuerLdap.name }}:{{ $ldapPort.port }}/dc=springframework,dc=org
    csirtmu.oidc.dummy.ldap.url=ldap://{{ $.Values.oidcIssuerLdap.name }}:{{ $ldapPort.port }}
    csirtmu.oidc.dummy.ldap.base=dc=springframework,dc=org
    csirtmu.oidc.dummy.ldap.userDn=cn=Directory Manager
    csirtmu.oidc.dummy.ldap.password={{ $.Values.oidcIssuerLdap.password }}
    csirtmu.oidc.dummy.ldap.admins=kypo-admin
    #
    # Postgres config
    #
    csirtmu.oidc.dummy.psql.url=jdbc:postgresql://{{ $.Values.global.postgres.dns }}:{{ $.Values.global.postgres.port }}/{{ $.Values.postgresServices.oidcIssuer.dbName }}
    csirtmu.oidc.dummy.psql.username={{ $.Values.postgresServices.oidcIssuer.dbUser }}
    csirtmu.oidc.dummy.psql.password={{ $.Values.postgresServices.oidcIssuer.dbName }}
{{- end }}
