apiVersion: v2
name: kypo-logstash
description: Logstash Helm chart used by KYPO CRP head services
type: application
version: 0.0.1
dependencies:
  - name: common
    version: 0.0.1
    repository: file://../common
