replicasCount: 1

image:
  url: registry.gitlab.ics.muni.cz:443/muni-kypo-crp/kypo-crp-artifact-repository/kypo-sandbox-service
  tag: v0.18.0

environments:
  - name: SERVICE_PRECONDITION
    value: uag-service:8084

mounts:
  - name: config
    extension: .yml
    mountPath: /app/
    isOneFile: true
    subPath: true
    type:
      secret:
        secretName: sandbox-service-secret
  - name: tls
    extension: .crt
    mountPath: /usr/local/share/ca-certificates/
    isOneFile: true
    subPath: false
    type:
      secret:
        secretName: kypo-certs
  - name: kypo-crp-proxy-key
    extension:
    mountPath: /root/.ssh/
    isOneFile: true
    subPath: true
    mode: 0600
    type:
      secret:
        secretName: kypo-crp-proxy-key
  - name: ansible-runner-vol
    extension:
    mountPath: /var/opt/kypo/kypo-ansible-runner-volumes
    isOneFile: false
    type:
      hostPath:
        path: /var/opt/kypo/kypo-ansible-runner-volumes
        type: Directory
  - name: docker-socket
    extension:
    mountPath: /var/run/docker.sock
    isOneFile: false
    type:
      hostPath:
        path: /var/run/docker.sock
        type: Socket

kypoHeadIp: 0.0.0.0
stackNamePrefix: default0
dnsNameServers:
  - 1.1.1.1
  - 1.0.0.1
osAuthUrl:
osApplicationCredentialId:
osApplicationCredentialSecret:
osConsoleType: spice-html5
openstackWorkerCount: 2
ansibleWorkerCount: 2
defaultWorkerCount: 2
sandboxBuildTimeout: 7200
sandboxDeleteTimeout: 3600
sandboxAnsibleTimeout: 7200
manFlavor: csirtmu.tiny1x2
proxyHost:
proxyUser:
proxyKey:
ansibleDockerNetwork: host

ansibleRunner:
  image:
    url: registry.gitlab.ics.muni.cz:443/muni-kypo-crp/kypo-crp-artifact-repository/kypo-ansible-runner
    tag: v1.3.5

gitConfig:
  type: INTERNAL
  server: 172.19.0.22
  sshPort: 30022
  restServerUrl: http://git-internal.kypo:5000/
  user: git
  privateKey:
  accessToken: no-gitlab-token
  ansibleNetworkingUrl: ssh://git@172.19.0.22:30022/repos/backend-python/ansible-networking-stage/kypo-ansible-stage-one.git
  ansibleNetworkingRev: v1.0.4
