{{- include "common.deployment.header" (dict "name" .Values.global.redis.serviceName "replicasCount" .Values.replicasCount) }}
{{- include "common.deployment.containers" (dict "name" .Values.global.redis.serviceName "ports" .Values.ports "Values" .Values) }}
