{{- if .Values.gitConfig.privateKey }}
apiVersion: v1
kind: Secret
metadata:
  name: git-external-key
  labels: {{- include "common.labels" (dict "name" .Values.global.services.sandbox.name "chart" .Chart "release" .Release "extraLabels" .Values.extraLabels) | nindent 4 }}
type: Opaque
data:
  git-ssh-key: {{ .Values.gitConfig.privateKey }}
{{- end }}
