{{- if .Values.kypoCrpGit.privateKey }}
apiVersion: v1
kind: Secret
metadata:
  name: git-external-key
  labels:
    app: {{ .Values.global.services.sandbox.name }}
type: Opaque
data:
  git-ssh-key: {{ .Values.kypoCrpGit.privateKey }}
{{- end }}
