{{- include "common.worker.deployment" (dict "name" (print .Values.global.services.sandbox.name "-worker-ansible") "replicaCount" .Values.ansibleWorkerCount  "workerType" "ansible" "Values" .Values) }}
