replicasCount: 1

image:
  url: registry.gitlab.ics.muni.cz:443/muni-kypo-crp/kypo-crp-artifact-repository/kypo-training-feedback-service
  tag: 22.06

mounts:
  - name: kypo-training-feedback
    extension: .properties
    mountPath: /app/etc/
    isOneFile: true
    subPath: false
    type:
      configMap:
        name: training-feedback-service-configmap
  - name: tls
    extension: .crt
    mountPath: /srv/
    isOneFile: true
    subPath: false
    type:
      secret:
        secretName: kypo-certs
