{{- $ports := list (dict "port" .Values.global.services.training.port "protocol" "TCP" "probe" true) -}}
{{- include "common.deployment.header" (dict "name" .Values.global.services.training.name "replicasCount" .Values.replicasCount) }}
{{- include "common.deployment.containers" (dict "name" .Values.global.services.training.name "ports" $ports "Values" .Values) }}
          lifecycle:
            postStart:
              exec:
                command:
                  - "/bin/bash"
                  - "-c"
                  - "/usr/local/openjdk-11/bin/keytool -importcert -alias kypo -file /srv/tls.crt -keystore /usr/local/openjdk-11/lib/security/cacerts -storepass changeit -noprompt"
{{- include "common.deployment.volumes" (dict "Values" .Values) }}
