apiVersion: v2
name: kypo-guacamole
description: A Helm chart deploying a KYPO CRP guacamole on Kubernetes
type: application
version: 0.0.1
appVersion: "1.3.0"
dependencies:
  - name: common
    version: 0.0.1
    repository: file://../common
