postgresServices:
  guacamole:
    dbName: kypo_guacamole_db
    dbUser: kypo_guacamole_user
    dbPassword: kypo_password

guacd:
  name: guacd
  image:
    url: guacamole/guacd
    tag: 1.3.0
  ports:
    - port: 4822
      protocol: TCP
      probe: true
  pvc:
    size: 500Mi
    storageClassName: longhorn

guacamole:
  name: guacamole
  replicasCount: 1
  image:
    url: registry.gitlab.ics.muni.cz:443/muni-kypo-crp/kypo-crp-artifact-repository/kypo-guacamole
    tag: 1.3.0
  ports:
    - port: 8080
      protocol: TCP
      probe: true
  guacamoleAdmin: guac-admin
  guacamoleAdminPassword: guac-admin
