{{- include "common.deployment.header" (dict "name" .Values.global.kypoLogstashServiceName "replicasCount" .Values.replicasCount) }}
{{- include "common.deployment.containers" (dict "name" .Values.global.kypoLogstashServiceName "ports" .Values.ports "Values" .Values) }}
{{- include "common.deployment.volumes" (dict "Values" .Values) }}
