apiVersion: v2
name: smart-assistant
description: Smart-assistant service Helm chart
type: application
version: 0.0.1
dependencies:
  - name: common
    version: 0.0.1
    repository: file://../common
