replicasCount: 1

image:
  url: registry.gitlab.ics.muni.cz:443/muni-kypo-crp/kypo-crp-artifact-repository/kypo-adaptive-smart-assistant-service
  tag: v1.0.31

mounts:
  - name: kypo-adaptive-smart-assistant
    extension: .properties
    mountPath: /app/etc/
    isOneFile: true
    subPath: true
    type:
      configMap:
        name: smart-assistant-configmap
