{{- with .Values.oidcIssuerLdap }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .name }}
type: Opaque
stringData:
  import-data.ldif: |-
    dn: ou=people,dc=springframework,dc=org
    objectclass: top
    objectclass: organizationalUnit
    ou: people
    {{- $users := $.Values.global.users }}
    {{- if (lookup "v1" "Secret" "kypo" "generated-users") }}
    {{- $users = concat $.Values.global.users ((lookup "v1" "Secret" "kypo" "generated-users").data.generatedUsers | b64dec | fromYamlArray) }}
    {{- end }}
    {{- range $users }}
    {{- if .password }}

    dn: uid={{ .sub }},ou=people,dc=springframework,dc=org
    objectclass: top
    objectclass: person
    objectclass: organizationalPerson
    objectclass: inetOrgPerson
    cn: {{ .fullName }}
    sn: {{ .familyName }}
    uid: {{ .sub }}
    userPassword: {{ .password }}
    displayName: "{{ .fullName }}"
    givenName: {{ .givenName }}
    mail: "{{ .email }}"
    {{- end }}
    {{- end }}
{{- end }}
